/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Slides3;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Hashtable;
import javax.swing.JLabel;

/**
 *
 * @author anhba
 */
public class JSliderDemo extends javax.swing.JFrame {

    /**
     * Creates new form JSliderDemo
     */
    public JSliderDemo() {
        initComponents();
        setLocationRelativeTo(null);
        Hashtable data = new Hashtable();
        String s[] = {"T1","T2","T3","T4","T5","T6","T7","T8","T9","T10","T11","T12"};
        for(int i = 0;i<12;i++){
        data.put(i, new JLabel(s[i]));
        }
        thang.setLabelTable(data);
        Calendar ca = Calendar.getInstance();
        ngay.setValue(ca.get(Calendar.DAY_OF_MONTH));
        thang.setValue(ca.get(Calendar.MONTH));
        nam.setValue(ca.get(Calendar.YEAR));
         dis();
        
    }
    
    void dis(){
        
        SimpleDateFormat s = new SimpleDateFormat("EEE, dd - MMM - yyyy)");
                int dd = ngay.getValue();
                int mm = thang.getValue();
                int yy = nam.getValue()-1900;
        
                Date d =  new Date(yy, mm, dd);
                
                txt.setText(s.format(d)+" ");
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ngay = new javax.swing.JSlider();
        thang = new javax.swing.JSlider();
        nam = new javax.swing.JSlider();
        txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ngay.setBackground(new java.awt.Color(102, 255, 102));
        ngay.setMajorTickSpacing(3);
        ngay.setMaximum(31);
        ngay.setMinimum(1);
        ngay.setMinorTickSpacing(1);
        ngay.setPaintLabels(true);
        ngay.setPaintTicks(true);
        ngay.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ngayStateChanged(evt);
            }
        });

        thang.setBackground(new java.awt.Color(255, 102, 102));
        thang.setMajorTickSpacing(1);
        thang.setMaximum(11);
        thang.setPaintLabels(true);
        thang.setPaintTicks(true);
        thang.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                thangStateChanged(evt);
            }
        });

        nam.setBackground(new java.awt.Color(255, 255, 153));
        nam.setMajorTickSpacing(5);
        nam.setMaximum(2030);
        nam.setMinimum(2000);
        nam.setPaintLabels(true);
        nam.setPaintTicks(true);
        nam.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                namStateChanged(evt);
            }
        });

        txt.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ngay, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                        .addComponent(thang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(ngay, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(thang, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(nam, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(txt, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ngayStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ngayStateChanged
        // TODO add your handling code here:
        dis();
    }//GEN-LAST:event_ngayStateChanged

    private void thangStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_thangStateChanged
        // TODO add your handling code here:
        dis();
    }//GEN-LAST:event_thangStateChanged

    private void namStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_namStateChanged
        // TODO add your handling code here:
        dis();
    }//GEN-LAST:event_namStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JSliderDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JSliderDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JSliderDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JSliderDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JSliderDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider nam;
    private javax.swing.JSlider ngay;
    private javax.swing.JSlider thang;
    private javax.swing.JTextField txt;
    // End of variables declaration//GEN-END:variables
}
